# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: React JS CI/CD

on:
  push:
    branches:
      - Master
  pull_request:
    branches:
      - Master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build/
      - name: Publish to npm
        uses: js-actions/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
          access: 'public'
          tag: 'latest'
